from django.urls import path

from .views import (
    client_pricing_preview,
    client_archive,
    client_create,
    client_edit,
    client_list,
    client_restore,
    order_create,
    order_detail,
    order_list,
    order_live_location,
    order_finish_confirm,
    order_custody_update,
    order_reopen,
    order_return_trip,
    order_split,
    order_driver_response_approve,
    order_driver_response_decline,
    order_tender_bid,
    order_tender_close,
    order_tender_open,
)

urlpatterns = [
    path("clients/", client_list, name="client-list"),
    path("clients/new/", client_create, name="client-create"),
    path("clients/preview/", client_pricing_preview, name="client-preview"),
    path("clients/<int:pk>/edit/", client_edit, name="client-edit"),
    path("clients/<int:pk>/archive/", client_archive, name="client-archive"),
    path("clients/<int:pk>/restore/", client_restore, name="client-restore"),
    path("", order_list, name="order-list"),
    path("new/", order_create, name="order-create"),
    path("<int:pk>/", order_detail, name="order-detail"),
    path("<int:pk>/live-location/", order_live_location, name="order-live-location"),
    path("<int:pk>/finish/confirm/", order_finish_confirm, name="order-finish-confirm"),
    path("<int:pk>/custody/", order_custody_update, name="order-custody-update"),
    path("<int:pk>/reopen/", order_reopen, name="order-reopen"),
    path("<int:pk>/return-trip/", order_return_trip, name="order-return-trip"),
    path("<int:pk>/split/", order_split, name="order-split"),
    path("<int:pk>/responses/<int:response_id>/approve/", order_driver_response_approve, name="order-response-approve"),
    path("<int:pk>/responses/<int:response_id>/decline/", order_driver_response_decline, name="order-response-decline"),
    path("<int:pk>/tender/open/", order_tender_open, name="order-tender-open"),
    path("<int:pk>/tender/bid/", order_tender_bid, name="order-tender-bid"),
    path("<int:pk>/tender/close/", order_tender_close, name="order-tender-close"),
]
