# Generated by Django 5.2.12 on 2026-03-23 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('completed_orders', models.PositiveIntegerField(default=0)),
                ('canceled_orders', models.PositiveIntegerField(default=0)),
                ('avg_final_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('on_time_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily KPI',
            },
        ),
        migrations.CreateModel(
            name='OrderAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_minutes', models.PositiveIntegerField(default=0)),
                ('transit_minutes', models.PositiveIntegerField(default=0)),
                ('delay_minutes', models.PositiveIntegerField(default=0)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('margin_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshot', to='orders.order')),
            ],
        ),
    ]
