# Generated by Django 5.2.12 on 2026-03-23 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('drivers', '0001_initial'),
        ('orders', '0002_client_order_client_price_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyFinanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_driver_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_margin', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('completed_orders', models.PositiveIntegerField(default=0)),
                ('canceled_orders', models.PositiveIntegerField(default=0)),
                ('issue_orders', models.PositiveIntegerField(default=0)),
                ('on_time_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ClientAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveIntegerField()),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('completed_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_margin', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='orders.client')),
            ],
            options={
                'ordering': ['-period_year', '-period_month', 'client__name'],
                'unique_together': {('client', 'period_year', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='DriverPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveIntegerField()),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('cancel_count', models.PositiveIntegerField(default=0)),
                ('issue_count', models.PositiveIntegerField(default=0)),
                ('on_time_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_delivery_time_minutes', models.PositiveIntegerField(default=0)),
                ('monthly_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('yearly_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rating_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='drivers.driver')),
            ],
            options={
                'ordering': ['-period_year', '-period_month', 'driver__full_name'],
                'unique_together': {('driver', 'period_year', 'period_month')},
            },
        ),
    ]
