# Generated by Django 5.2.12 on 2026-03-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_monthlyfinancereport_clientanalyticssnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientanalyticssnapshot',
            name='client_rating_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='clientanalyticssnapshot',
            name='yearly_completed_orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
