# Generated by Django 5.2.12 on 2026-03-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_clientanalyticssnapshot_client_rating_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('rating_completed_weight', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('rating_quality_weight', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('sla_breach_penalty_weight', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics setting',
                'verbose_name_plural': 'Analytics settings',
            },
        ),
        migrations.AddField(
            model_name='clientanalyticssnapshot',
            name='sla_breach_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientanalyticssnapshot',
            name='sla_breach_ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
