# Generated by Django 5.2.12 on 2026-03-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_analyticssettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssettings',
            name='sla_base',
            field=models.CharField(choices=[('pickup_time', 'Pickup time'), ('actual_start_at', 'Actual start time'), ('explicit_deadline', 'Explicit order deadline')], default='pickup_time', max_length=30),
        ),
    ]
