# Generated by Django 5.2.12 on 2026-03-23 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_analyticssettings_sla_base'),
        ('drivers', '0001_initial'),
        ('orders', '0004_order_actual_start_at_order_sla_deadline_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('sla_escalation', 'SLA escalation'), ('route_deviation', 'Route deviation')], max_length=40)),
                ('threshold_minutes', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(max_length=255)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_events', to='drivers.driver')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('order', 'alert_type', 'threshold_minutes')},
            },
        ),
    ]
