# Generated by Django 5.2.12 on 2026-03-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alertevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertevent',
            name='alert_type',
            field=models.CharField(choices=[('sla_escalation', 'SLA escalation'), ('route_deviation', 'Route deviation'), ('gps_spoofing', 'GPS spoofing risk'), ('impossible_speed', 'Impossible speed'), ('idle_anomaly', 'Long idle anomaly')], max_length=40),
        ),
    ]
