# Generated by Django 5.2.12 on 2026-03-25 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_alter_alertevent_alert_type'),
        ('orders', '0005_order_geofence_polygon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertevent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='orders.order'),
        ),
    ]
