# Generated by Django 5.2.12 on 2026-03-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alter_alertevent_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfinancereport',
            name='net_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='monthlyfinancereport',
            name='total_extra_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='monthlyfinancereport',
            name='total_fuel_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='monthlyfinancereport',
            name='total_penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
