# Generated by Django 5.2.12 on 2026-03-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_monthly_finance_cost_breakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertevent',
            name='alert_type',
            field=models.CharField(choices=[('sla_escalation', 'SLA escalation'), ('route_deviation', 'Route deviation'), ('gps_spoofing', 'GPS spoofing risk'), ('impossible_speed', 'Impossible speed'), ('idle_anomaly', 'Long idle anomaly'), ('driver_doc_expired', 'Driver documents expired'), ('driver_ketdik_webapp', 'Haydovchi «Ketdik» (marshrut mini-ilova)'), ('fuel_shortage', 'Fuel shortage (loaded vs delivered)')], max_length=40),
        ),
    ]
