# Generated by Django 5.2.12 on 2026-03-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_alter_alertevent_alert_type'),
        ('drivers', '0007_alter_driverdeliveryreview_stars'),
        ('orders', '0010_orderextraexpense'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['order', 'alert_type'], name='analytics_a_order_i_54b9e3_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['alert_type', 'resolved'], name='analytics_a_alert_t_fa1c0d_idx'),
        ),
    ]
