# Generated by Django 5.2.12 on 2026-03-23 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_geofence_polygon_and_more'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder_name', models.CharField(max_length=120)),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('eta_minutes', models.PositiveIntegerField(default=0)),
                ('quality_score', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['score', 'eta_minutes', 'bid_price'],
            },
        ),
        migrations.AddField(
            model_name='pricequote',
            name='distance_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pricequote',
            name='empty_return_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pricequote',
            name='empty_return_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pricequote',
            name='peak_coef',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name='pricequote',
            name='wait_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pricequote',
            name='wait_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricequote',
            name='weight_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pricequote',
            name='weight_ton',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='TenderSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_by', models.CharField(blank=True, max_length=120)),
                ('duration_minutes', models.PositiveIntegerField(default=5)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_selected_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_sessions', to='pricing.tenderbid')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_sessions', to='orders.order')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='pricing.tendersession'),
        ),
    ]
