# Generated by Django 5.2.12 on 2026-03-24 10:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
        ('drivers', '0001_initial'),
        ('orders', '0005_order_geofence_polygon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverOfferResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('accept', 'Qabul'), ('reject', 'Rad'), ('issue', 'Muammo')], max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('declined', 'Rad etildi')], default='pending', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('reviewed_by', models.CharField(blank=True, max_length=120)),
                ('responded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_responses', to='drivers.driver')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_responses', to='orders.order')),
            ],
            options={
                'ordering': ['-responded_at'],
                'unique_together': {('order', 'driver')},
            },
        ),
    ]
