# Generated by Django 5.2.12 on 2026-03-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_driverofferresponse'),
        ('drivers', '0007_alter_driverdeliveryreview_stars'),
        ('orders', '0010_orderextraexpense'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['driver', 'order'], name='dispatch_as_driver__f36f08_idx'),
        ),
    ]
