# Generated by Django 5.2.12 on 2026-03-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_issued_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_photo_file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='driver',
            name='registration_photo_file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='calibration_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_document_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_photo_file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tanker_document_photo_file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
