# Generated by Django 5.2.12 on 2026-03-25 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_registration_submitted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverVerificationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_audits', to='drivers.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
