# Generated by Django 5.2.12 on 2026-03-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driververificationaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rating_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
    ]
