# Generated by Django 5.2.12 on 2026-03-23 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_telegrammessagelog_order'),
        ('orders', '0005_order_geofence_polygon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessagelog',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='telegrammessagelog',
            name='signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='telegrammessagelog',
            name='source_ip',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='CriticalActionConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('action', models.CharField(max_length=40)),
                ('actor_id', models.BigIntegerField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_confirmations', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
