# Generated by Django 5.2.12 on 2026-03-24 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_telegrammessagelog_dedupe_key_and_more'),
        ('drivers', '0002_driver_license_expires_at_driver_license_issued_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverOnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(unique=True)),
                ('step', models.CharField(default='idle', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_states', to='drivers.driver')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
