# Generated by Django 5.2.12 on 2026-03-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_driveronboardingstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('group_type', models.CharField(choices=[('order_post', 'Yuklarni post qilish guruhi'), ('ops_notify', 'Xabarnoma (ops/dispatcher) guruhi')], max_length=20)),
                ('chat_id', models.CharField(help_text='Masalan: -1001234567890', max_length=50)),
                ('message_thread_id', models.IntegerField(blank=True, help_text='Forum topic ID (ixtiyoriy)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group_type', '-is_active', '-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('group_type',), name='uniq_active_telegram_group_per_type')],
            },
        ),
    ]
