# Generated by Django 5.2.12 on 2026-03-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_telegramgroupconfig'),
        ('drivers', '0007_alter_driverdeliveryreview_stars'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='driveronboardingstate',
            index=models.Index(fields=['telegram_user_id', 'is_active'], name='bot_drivero_telegra_2259ce_idx'),
        ),
    ]
