# Generated by Django 5.2.12 on 2026-03-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_alter_driverdeliveryreview_stars'),
        ('orders', '0010_orderextraexpense'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='locationping',
            index=models.Index(fields=['order', 'captured_at'], name='tracking_lo_order_i_a2b8d5_idx'),
        ),
        migrations.AddIndex(
            model_name='locationping',
            index=models.Index(fields=['driver', 'captured_at'], name='tracking_lo_driver__b83bec_idx'),
        ),
    ]
