# Generated by Django 5.2.12 on 2026-03-23 08:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('cargo_type', models.CharField(max_length=120)),
                ('weight_ton', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pickup_time', models.DateTimeField()),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_phone', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('price_suggested', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('offered', 'Offered'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('issue', 'Issue')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('new', 'New'), ('offered', 'Offered'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('issue', 'Issue')], max_length=20)),
                ('to_status', models.CharField(choices=[('new', 'New'), ('offered', 'Offered'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('issue', 'Issue')], max_length=20)),
                ('changed_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_logs', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
