# Generated by Django 5.2.12 on 2026-03-23 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_client_order_client_price_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contract_base_rate_per_ton',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='client',
            name='contract_min_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_terms',
            field=models.CharField(choices=[('prepaid', 'Prepaid'), ('deferred', 'Deferred')], default='deferred', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='sla_minutes',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='order',
            name='is_return_trip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='parent_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_children', to='orders.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_terms',
            field=models.CharField(choices=[('prepaid', 'Prepaid'), ('deferred', 'Deferred')], default='deferred', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='return_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_orders', to='orders.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='split_group_code',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name='order',
            name='split_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='split_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ContractTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_type', models.CharField(blank=True, max_length=120)),
                ('from_location', models.CharField(blank=True, max_length=255)),
                ('to_location', models.CharField(blank=True, max_length=255)),
                ('rate_per_ton', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_tariffs', to='orders.client')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
