# Generated by Django 5.2.12 on 2026-03-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_client_contract_base_rate_per_ton_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sla_deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
