# Generated by Django 5.2.12 on 2026-03-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_actual_start_at_order_sla_deadline_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='geofence_polygon',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='route_deviation_threshold_km',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='route_polyline',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
