# Generated by Django 5.2.12 on 2026-03-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_geofence_polygon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_quantity_uom',
            field=models.CharField(choices=[('ton', 'Tonna'), ('kg', 'Kg'), ('liter', 'Litr')], default='ton', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_recorded_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='density_kg_per_liter',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='loaded_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='loaded_quantity_uom',
            field=models.CharField(choices=[('ton', 'Tonna'), ('kg', 'Kg'), ('liter', 'Litr')], default='ton', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='loaded_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='loaded_recorded_by',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
