# Generated by Django 5.2.12 on 2026-03-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_quantity_custody'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shortage_flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shortage_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shortage_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shortage_penalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
